version: '3.7'
services:
    flask:
        build: .
        ports:
            - "5001:5001"
        volumes:
            - .:/app
        environment:
            - PORT=5001
            - HOST_MONGO=mongodb
            - HOST_REDIS=redis
        depends_on:
            - redis
            - mongodb
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
    mongodb:
        image: mongo:4.2.3
        ports:
            - "27018:27017"